---
language: ruby

before_install: rvm get head

rvm:
  - 2.2.4
  - 2.3.0
  - ruby-head
  - rbx-2
  - jruby-9.0.5.0
  - jruby-head

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
